Add ability to mute keywords from chat
tommyxchow/frosty pull request #413
Opened 2024-11-10 13:41 UTC by zeykafx

This PR adds the ability for users to mute specific keywords in the chat.
It adds a section in the chat settings. Besides the bottom sheet with a text field, there is a switch that makes the app only match whole words instead of words containing the keyword (for example, if someone wants to mute "W"s but doesn't want words with "w" to be filtered). 

Related to issue #400 

https://github.com/user-attachments/assets/b067f4ed-f4d4-4ff3-b15f-dfb8cadf99de

2024-11-11 09:13 UTC, zeykafx commented on lib/screens/settings/stores/settings_store.dart
> +  FocusNode textFieldFocusNode = FocusNode();
I 100% agree, I wasn't sure if you were okay with stateful widgets!

2024-11-12 03:24 UTC, tommyxchow requested changes
Pretty cool solution but for this case and simplicity, I think we should just use a normal list/array, then instead of mutating the list/array, re-assign it in an immutable style so that Mobx will detect that the variable changed.

2024-11-12 03:24 UTC, tommyxchow commented on lib/screens/settings/stores/settings_store.dart
> +  ObservableList<String> mutedWords = getDefaultMutedWords();
```suggestion
  @JsonKey(defaultValue: getDefaultMutedWords)
  @observable
  var mutedWords = defaultMutedWords;
```

From thereon we can rely on immutability instead of mutations for the list changes. So anytime we want to edit the list just reassign the whole thing and Mobx will detect the changes.

2024-11-12 03:24 UTC, tommyxchow commented on lib/screens/settings/widgets/settings_muted_words.dart
> +    settingsStore.mutedWords.add(text);
With the change in settings store, Mobx should be able to detect changes if we do something like this:

```suggestion
    settingsStore.mutedWords = [...settingsStore.mutedWords, text];
```

2024-11-12 03:24 UTC, tommyxchow commented on lib/screens/settings/stores/settings_store.dart
> +  }
For simplicity, I think we should just make `defaultMutedWords` a normal string array (follow up in next comment):
```suggestion
static const defaultMutedWords = <String>[];
```

2024-11-12 07:49 UTC, zeykafx commented
Sounds good, I’ve made the changes. It was indeed a bit overkill, perhaps!

2024-11-13 02:42 UTC, tommyxchow approved these changes
Looks great, thank you so much!

2024-11-13 02:42 UTC, merged